INSERT INTO TRANSACTION(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Supermarket','Gap Store Woodfiled MalL, IL','123.4', now());
INSERT INTO TRANSACTION(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Supermarket','Best Buy Schaumburg IL','400', now());
INSERT INTO TRANSACTION(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Restaurants','Chees Cake Factory Woodfiled IL','12.5', now());
INSERT INTO TRANSACTION(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Restaurants','Starbucks Hoffman Estates IL','18.5', now());
INSERT INTO TRANSACTION(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Restaurants','Discover RAK Cafe, Riverwoods IL','13.5', now());
INSERT INTO TRANSACTION(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Entertainment','AMC South Barrington IL','48.6', now());
INSERT INTO TRANSACTION(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Entertainment','Urban Air Bloomingdale, IL','70', now());
INSERT INTO TRANSACTION(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Travel','United Airlines, San Fransisco CA','700', now());
INSERT INTO TRANSACTION(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Travel','United Luggage checkin, Ohare IL','36.4', now());
INSERT INTO TRANSACTION(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Gas','Caseys convenience, Riverwoods IL','13.5', now());
INSERT INTO TRANSACTION(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Healthcare','St. Alexis, Hoffman Estates IL','170.5', now());
INSERT INTO TRANSACTION(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Healthcare','Associates in pediatrics, Streamwood IL','125', now());
INSERT INTO TRANSACTION(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Healthcare','Amita Health, Schaumburg IL','125', now());
INSERT INTO TRANSACTION(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Healthcare','Amita Health, Schaumburg IL','125', now());
INSERT INTO TRANSACTION2(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Recent Transactions','Amita Health, Schaumburg IL','125', now());
INSERT INTO TRANSACTION2(CATEGORY, DESCRIPTION, AMOUNT, CREATEDDATE) VALUES('Recurring','Amita Health, Schaumburg IL','125', now());

