CREATE TABLE TRANSACTION(
    ID BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY, 
    CATEGORY VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    AMOUNT NUMERIC(20,2) NOT NULL,
    CREATEDDATE TIMESTAMP WITH TIME ZONE NOT NULL
);